server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db:5432/asana
    username: asana
    password: asana

  jpa:
    hibernate:
      ddl-auto: none   # IMPORTANT: let schema.sql run
    show-sql: true

  sql:
    init:
      mode: always     # ensures schema.sql executes at startup

